-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v2.1.0
    hooks:
    -   id: detect-private-key
        files: ^(?!\.?git-crypt)
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        language_version: python3
        files: ^tf|-|\.(py|tfvars|tf|tfenv|env|yml|yaml|pem|key|mock)$
    -   id: end-of-file-fixer
        files: ^tf|-|\.(py|env|yml|yaml|pem|key|mock)$
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-ast
    -   id: debug-statements
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E501
    -   id: double-quote-string-fixer
    -   id: check-docstring-first
    -   id: pretty-format-json
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
-   repo: git://github.com/dnephin/pre-commit-golang
    sha: v0.3.2
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
    -   id: validate-toml
    -   id: no-go-testing
