---
version: "3"

includes:
  changelog: ./provision/task/changelog.yml
  confluence: ./provision/task/confluence.yml
  python: ./provision/task/python.yml
  git: ./provision/task/git.yml
  docs: ./provision/task/docs.yml
  docker: ./provision/task/docker.yml
  version: ./provision/task/version.yml
  plantuml: ./provision/task/plantuml.yml
  prettier: ./provision/task/prettier.yml
  sonar: ./provision/task/sonar.yml
  go: ./provision/task/go.yml
  diagrams: ./provision/diagrams/Taskfile.yml

env:
  DOCKER:
    sh: docker --version 2> /dev/null || echo "not exist"
  PYTHON:
    sh: python --version 2> /dev/null || echo "not exist"
  GO:
    sh: go version 2> /dev/null || echo "not exist"
  NODE:
    sh: node --version 2> /dev/null || echo "not exist"
  APP_TAG:
    sh: git describe --tags $(git rev-list --tags --max-count=1) 2> /dev/null || echo "0.0.0"
  README_YAML: provision/generators/README.yaml
  README_TEMPLATE: provision/templates/README.tpl.md
  README_INCLUDES: file://

dotenv:
  - .env

vars:
  PROJECT_NAME: learn-go
  GROUP_NAME: luismayta
  ORGANIZATION: luismayta
  DOCKER_PLATFORM: linux/amd64
  REVIEWERS: luismayta
  PYTHON_VERSION: 3.11.5
  NODE_VERSION: 16.6.1
  TERRAFORM_VERSION: 1.4.6
  GIT_IGNORES: python,node,go,zsh,sonar,java,maven,intellij+all,terraform,linux
  COMMIT: $(git rev-parse HEAD)
  RELEASE_DIR: ./release
  DATE: $(date +%s)
  GOLANGCI_VERSION: 1.42.0
  README_FILE: README.md
  GIT_IGNORES_CUSTOM: |
    bin
    .scannerwork
    .secrets
    public
    TMP_CHANGELOG.md
    .task
    .terraform.lock.hcl
    *.lock.hcl
    *.lock
    *.zip
    .external_modules
    vendor
    .DS_Store

tasks:
  default:
    deps:
      - task: check
    cmds:
      - cmd: echo Application {{.PROJECT_NAME}}
        silent: true
      - task: version:default
      - task: summary
      - cmd: task -l
    silent: true

  summary:
    desc: "Summary information"
    cmds:
      - echo Go available {{.GO}}
      - echo Python available {{.PYTHON}}
      - echo Docker available {{.DOCKER}}
      - echo Node available {{.NODE}}
    silent: true

  check:
    desc: "Check all dependencies"
    deps:
      - python:check
      - changelog:check
      - git:check
      - docs:check

  readme:
    run: once
    desc: Generate Readme
    silent: true
    cmds:
      - >-
        gomplate --file {{.README_TEMPLATE}}
        --out {{.README_FILE}}
        --datasource config={{.README_YAML}}
        --datasource includes={{.README_INCLUDES}}
      - task: prettier

  prettier:
    run: once
    desc: Execute prettier files
    cmds:
      - task: python:fmt
      - task: go:fmt
      - task: prettier:all

  test:
    run: once
    desc: Execute of test
    cmds:
      - task: go:test

  upgrade:
    desc: Execute upgrade packages
    cmds:
      - poetry update
      - poetry run pre-commit autoupdate

  start:
    run: once
    desc: Execute project
    cmds:
      - go run ./main.go

  setup:
    desc: Setup dependences of project
    cmds:
      - >-
        [ -e ".env" ] || cp -rf .env.example .env
      - task: python:setup
      - task: python:precommit
      - task: go:setup
      - task: git:setup

  environment:
    desc: Setup environment of project
    cmds:
      - task: python:environment

  generate:
    desc: Generate files
    cmds:
      - task: go:mockery
      - task: go:generate

  help:
    cmds:
      - cmd: |
          echo 'Use "task --list" to get a list of all available tasks with a short description of what they do.'
          echo 'There are some more tasks used as dependencies for other tasks.'
          echo 'You can view them with "task --list-all".'
        silent: true
