// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// Injectors from wire.go:

// wire_gen.go
func InitializeEvent(phrase string) IEvent {
	iMessage := NewMessage(phrase)
	iGreeter := NewGreeter(iMessage)
	iEvent := NewEvent(iGreeter)
	return iEvent
}
